project_name: goshod
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm 
      - 386
    id: "import_disqus_cli"
    dir: .
    main: .
