name: Release Go binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64, arm, 386]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -p=1 -timeout=0 ./...
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "GoShod"
          ldflags: "-s -w"
          extra_files: LICENSE README.md
